<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<InternalsVisibleTo Include="InvestmentPortfolioTracker.Infrastructure.IntegrationTests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\InvestmentPortfolioTracker.Core\InvestmentPortfolioTracker.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" />
		<PackageReference Include="Dapper" />
		<PackageReference Include="Google.Apis.Auth" />
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Http" />
	</ItemGroup>

</Project>
